# ===================================================================
# Health Check
# ===================================================================

name: Health Check

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# github scheduler not supported seconds cron feature
on:
  schedule:
    # Just Run Every 5minute https://crontab.guru
    - cron: '*/1 * * * *'
  push:
    branches: 'main'

# Job Tasks
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      # Echo
      - name: echo job
        run: echo "Health Check"

      # Start Job
      - name: start Job
        run: date

      - name: oksusu health check
        run: |
          curl -X 'GET' \
          'https://api.oksusu.site/api/v1/metadata/version' \
          -H 'accept: application/json'

      # End Job
      - name: end Job
        run: date
